//==============================================================================
// crlp_tb_top.sv : top-level testbench for the CRLP agent + stub DMAC
//==============================================================================
`ifndef CRLP_TB_TOP_SV
`define CRLP_TB_TOP_SV

module crlp_tb_top;
  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import crlp_pkg::*;
  `include "crlp_test.svh"

  // Interface instance (clk is generated by the agent's driver).
  crlp_if bus ();

  // DUT under test (stub responder).
  crlp_dut_stub #(.ACCEPT_DELAY(3)) dut (.bus(bus));

  initial begin
    uvm_config_db#(virtual crlp_if)::set(null, "uvm_test_top", "vif", bus);
    run_test("crlp_base_test");
  end

  // Safety net global timeout.
  initial begin
    #1ms;
    `uvm_fatal("TB_TOP", "Global timeout reached")
  end

  // Optional waveform dump.
  initial begin
    if ($test$plusargs("DUMP")) begin
      $dumpfile("crlp.vcd");
      $dumpvars(0, crlp_tb_top);
    end
  end

endmodule

`endif // CRLP_TB_TOP_SV
