//==============================================================================
// crlp_if.sv
//   Clock / Reset / Low-Power (Q-Channel + P-Channel) interface for the DMAC.
//
//   Direction convention is taken from the DMAC (DUT) point of view, exactly
//   as in the spec tables A-1/A-2/A-3.  This agent models the *external*
//   clock controller + power controller + reset generator, so it DRIVES the
//   DUT inputs and MONITORS the DUT outputs.
//
//     Agent drives  (DUT inputs) : clk, resetn, aclken_m0, aclken_m1, pclken,
//                                  clk_qreqn, preq, pstate
//     Agent samples (DUT outputs): clk_qacceptn, clk_qdeny, clk_qactive,
//                                  paccept, pdeny
//==============================================================================
`ifndef CRLP_IF_SV
`define CRLP_IF_SV

`timescale 1ns/1ps
interface crlp_if;

  // ---- Table A-1 : Clock and reset ----------------------------------------
  logic        clk;         // Clock input (generated by this agent)
  logic        resetn;      // Active-LOW reset. LOW async, HIGH synchronous
  logic        aclken_m0;   // AXI5 clock enable, M0
  logic        aclken_m1;   // AXI5 clock enable, M1
  logic        pclken;      // APB4 clock enable

  // ---- Table A-2 : Q-Channel (clock controller) ---------------------------
  logic        clk_qreqn;    // controller -> DMAC : quiescence entry/exit req
  logic        clk_qacceptn; // DMAC -> controller : accept
  logic        clk_qdeny;    // DMAC -> controller : deny
  logic        clk_qactive;  // DMAC -> controller : active / wants to exit

  // ---- Table A-3 : P-Channel (power controller) ---------------------------
  logic        preq;         // controller -> DMAC : power state change request
  logic [3:0]  pstate;       // controller -> DMAC : requested power state
  logic        paccept;      // DMAC -> controller : accept
  logic        pdeny;        // DMAC -> controller : deny

  // Note: clk is generated in the driver's clock engine (procedural), it is
  // NOT driven from a clocking block.  The LPI handshakes are always performed
  // while the clock is running, so sampling/driving them from clocking blocks
  // is safe.

  //--------------------------------------------------------------------------
  // Driver clocking block : drive LPI request signals, sample responses
  //--------------------------------------------------------------------------
  clocking drv_cb @(posedge clk);
    default input #1step output #1ns;
    output clk_qreqn;
    output preq;
    output pstate;
    input  clk_qacceptn;
    input  clk_qdeny;
    input  clk_qactive;
    input  paccept;
    input  pdeny;
  endclocking

  //--------------------------------------------------------------------------
  // Monitor clocking block : sample everything (passive)
  //--------------------------------------------------------------------------
  clocking mon_cb @(posedge clk);
    default input #1step;
    input resetn, aclken_m0, aclken_m1, pclken;
    input clk_qreqn, clk_qacceptn, clk_qdeny, clk_qactive;
    input preq, pstate, paccept, pdeny;
  endclocking

  modport drv (clocking drv_cb, output clk, output resetn,
               output aclken_m0, output aclken_m1, output pclken);
  modport mon (clocking mon_cb, input clk, input resetn);

endinterface

`endif // CRLP_IF_SV
